services:
  app:
    build:
      args:
        user: kyle
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /var/www/mysql-master-slave
    volumes:
      - ./:/var/www/mysql-master-slave
    networks:
      - app-network
  db-master:
    image: mysql:8.0
    container_name: db-master
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    command: --server-id=1 --log-bin=mysql-bin --binlog-format=row
    ports:
      - "4306:3306"
    expose:
      - 4306
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - app-network
  db-slave:
    image: mysql:8.0
    container_name: db-slave
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    depends_on:
      - db-master
    command: --server-id=2 --log-bin=mysql-bin --binlog-format=row
    ports:
      - "4307:3306"
    expose:
      - 4307
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - app-network
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 9090:80
    volumes:
      - ./:/var/www/mysql-master-slave
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
